export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { Flex, Text, HStack } from "@chakra-ui/react"
import Link from "next/link";
import {BsFillHouseDoorFill} from "react-icons/bs";
import { BLUE_BACKGROUND_COLOUR_HEX } from "./config";

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <Flex
        height="5vw"
        direction="row"
        alignItems="center"
        justifyContent="space-around"
        background={BLUE_BACKGROUND_COLOUR_HEX}
        borderRadius="1px"
        borderColor="black"
        >
          <Link
            href={"/"}
          >
            <Flex
              direction="row"
              align="center"
            >
              <BsFillHouseDoorFill className="headingLink" size="3vw"/>
              {/* <p size="3px" className="headingLink">Home</p> */}
            </Flex>
          </Link>
        </Flex>
        {children}
      </body>
    </html>
  )
}
